### ISSUE TITLE
PKTGNR - 001 : Api Access Exception : registrationprocessor/v1/registrationstatus/sync

### ISSUE THREAD

**Issue by namatedev** [mosip/mosip-infra#69]
I have followed the instruction for the sandbox https://github.com/mosip/mosip-infra/blob/master/deployment/sandbox/README.md

The setup for all blocks (kernerl + pre-reg + reg-proc + id auth) went well and the setup logs showed failure=0

The issue I have is with the test to upload a packet as in the above guide.

In the MOSIP Registration Processor > Steps to upload a packet into Reg Proc, if we follow the recommended steps, and we try the url in the browser :

http://<public_ip_address>/v1/utility/packetgenerator/createAndUpload

The error returned is some error of type : "Api Access Exception"

{
    "id": "io.mosip.packetgenerator.uploader",
    "version": "version",
    "responsetime": "2020-05-12T13:30:26.102Z",
    "metadata": null,
    "errors": [
        {
            "errorCode": "PKTGNR - 001",
            "message": "Api Access Exception {\"timestamp\":\"2020-05-12T13:30:26.017+0000\",\"status\":500,\"error\":\"Internal Server Error\",\"message\":\"No message available\",\"path\":\"/registrationprocessor/v1/registrationstatus/sync\"}"
        }
    ],
    "response": null

Please advise

**Comment by namatedev** [comment]
Furthermore when investigating the involved dockers logs, it seems at the moment where the packet is sent, this error shows : 

2020-05-13 12:34:53,615 [http-nio-8083-exec-6] ERROR [o.a.j.l.DirectJDKLog].log.182 : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.NullPointerException] with root cause
java.lang.NullPointerException: null
at io.mosip.registration.processor.core.util.DigitalSignatureUtility.getDigitalSignature(DigitalSignatureUtility.java:76)
at io.mosip.registration.processor.status.api.controller.RegistrationSyncController.syncRegistrationController(RegistrationSyncController.java:119)

So it is something related to getDigitalSignature

The receiving docker is : 

mosipid/registration-processor-registration-status-service:1.0.6

**Comment by pjoshi751** [comment]
@namatedev  we have now moved to sandbox-v2  which is a full MOSIP sandbox setup.   Single machine sandbox is deprecated.

**Comment by namatedev** [comment]
Thanks @pjoshi751 for let know. Is the registration client working against the sandbox-v2? Or any way to test the registration upload packet use case against the sandbox-v2?

**Comment by pjoshi751** [comment]
@namatedev  Can you let me me know if your objective is to test reg client, sandbox or both?  Just to understanding so that we can make it easier for you.

**Comment by namatedev** [comment]
Yes, indeed the goal is to test the registration use case against a setup of MOSIP server. Thanks @pjoshi751
