### ISSUE TITLE
'Failed: No Internet Connection' on Reglient

### ISSUE THREAD

**Issue by 0xabdi** [mosip/mosip-infra#696]
I am getting the below error when I try to login to the regclient using the user `110011` and password `MOSIP`.

![image](https://user-images.githubusercontent.com/17492419/121894774-d075e680-cd1f-11eb-8f9b-84f24b349791.png)

I  have set the `mosip.hostname`'s environment variable value to `console.sb` which is the hostname of my console VM.
![image](https://user-images.githubusercontent.com/17492419/121895085-2480cb00-cd20-11eb-80e6-aae6baa42e29.png)

**Comment by 0xabdi** [comment]
I have tracked down the issue to this log entry in `reg-client/logs/registration`:

`2021-06-21T15:06:35+02:00 - [io.mosip.registration.util.healthcheck.RegistrationAppHealthCheckUtil] - ERROR - REGISTRATION - REGISTRATIONAPPHEALTHCHECKUTIL - ISNETWORKAVAILABLEfalse - REGISTRATION - REG - No Internet Access.javax.net.ssl.SSLHandshakeException: No subject alternative DNS name matching console.sb found.`

Would appreciate any ideas on how to fix this.

**Comment by 0xabdi** [comment]
Seems like the issue is related to the self-signed certificates that my MOSIP deployment is using. I have tried the resolution steps outlined here (https://stackoverflow.com/questions/29157861/java-certificateexception-no-subject-alternative-names-matching-ip-address) with no success.

**Comment by 0xabdi** [comment]
So, I resolved the initial issue by generating a new self-signed certificate for nginx and adding `console.sb` as the certificate's `Common Name (CN)`. The reason being, by default, MOSIP uses the server's IP address as the `CN` when it is generating the self-signed certificate as mentioned here https://stackoverflow.com/questions/29157861/java-certificateexception-no-subject-alternative-names-matching-ip-address. Here is a link on how to generate a self-signed certificate for nginx: https://www.digitalocean.com/community/tutorials/how-to-create-a-self-signed-ssl-certificate-for-nginx-on-centos-7. This should not be an issue when using a CA-issued certificate since this is issued to the domain name registered under MOSIP and not the IP address.

However, there is a new error now when I try to login to the reg-client. It throws a `Failed: Sync Configuration Failure` error as shown below.
![image](https://user-images.githubusercontent.com/17492419/124417869-6c60a400-dd5a-11eb-89ef-290af1d38a29.png)

**Comment by 0xabdi** [comment]
Here are the ERROR log entries generated upon application launch:
log file name: `packetutility`
```
2021-07-05T07:19:32+02:00 - [io.mosip.kernel.keymanagerservice.service.impl.KeymanagerServiceImpl] - ERROR - sessionId - keyAlias - 0 - Initial Key generation process not completed.

...

2021-07-05T07:19:36+02:00 - [io.mosip.kernel.keymanagerservice.service.impl.KeymanagerServiceImpl] - ERROR - sessionId - currentKeyAlias - Error - Key Not found in HSM, keystore might have loaded as offline.KER-KMA-007 --> Keystore loaded as offline, Retrivial of Private is not allowed.
```

log file name: registration
```
2021-07-05T07:19:12+02:00 - [io.mosip.registration.exception.RegBaseCheckedException] - ERROR - REGISTRATION - CHECKED_EXCEPTION - REGISTRATION - REG - REG-SCHEMA-001-->No Schema Found
2021-07-05T07:19:12+02:00 - [io.mosip.registration.controller.BaseController] - ERROR - REGISTRATION - BASE - BASE_CONTROLLER - REGISTRATION - REG - io.mosip.registration.exception.RegBaseCheckedException: REG-SCHEMA-001 --> No Schema Found
	at io.mosip.registration.dao.impl.IdentitySchemaDaoImpl.getLatestEffectiveUISchema(IdentitySchemaDaoImpl.java:68)
	at io.mosip.registration.service.impl.IdentitySchemaServiceImpl.getLatestEffectiveUISchema(IdentitySchemaServiceImpl.java:32)
	at io.mosip.registration.controller.BaseController.loadUIElementsFromSchema(BaseController.java:1543)
	at io.mosip.registration.controller.auth.LoginController.showUserNameScreen(LoginController.java:329)
	at io.mosip.registration.controller.auth.LoginController.loadInitialScreen(LoginController.java:279)
	at io.mosip.registration.controller.Initialization.start(Initialization.java:54)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(Unknown Source)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(Unknown Source)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

...

2021-07-05T07:19:39+02:00 - [io.mosip.registration.service.sync.impl.TPMPublicKeySyncServiceImpl] - ERROR - REGISTRATION - TPM_PUBLIC_KEY_SYNC - SYNC_TPM_PUBLIC_KEY - REGISTRATION - REG - Error while uploading the TPM public key
2021-07-05T07:19:39+02:00 - [io.mosip.registration.service.sync.impl.TPMPublicKeySyncServiceImpl] - ERROR - REGISTRATION - TPM_PUBLIC_KEY_SYNC - SYNC_TPM_PUBLIC_KEY - REGISTRATION - REG - Error Code: KER-SNC-155	 Error Message: Machine not found

...

2021-07-05T07:19:39+02:00 - [io.mosip.registration.exception.RegBaseCheckedException] - ERROR - REGISTRATION - CHECKED_EXCEPTION - REGISTRATION - REG - REG-TPK-001-->Exception while uploading the TPM Public Key
2021-07-05T07:19:39+02:00 - [io.mosip.registration.exception.RegBaseCheckedException] - ERROR - REGISTRATION - CHECKED_EXCEPTION - REGISTRATION - REG - REG-TPK-001-->Exception while uploading the TPM Public Key-->io.mosip.registration.exception.RegBaseCheckedException: REG-TPK-001 --> Exception while uploading the TPM Public Key
	at io.mosip.registration.service.sync.impl.TPMPublicKeySyncServiceImpl.syncTPMPublicKey(TPMPublicKeySyncServiceImpl.java:97)
	at io.mosip.registration.service.login.impl.LoginServiceImpl.initialSync(LoginServiceImpl.java:319)
	at io.mosip.registration.controller.auth.LoginController$3$1.call(LoginController.java:1015)
	at io.mosip.registration.controller.auth.LoginController$3$1.call(LoginController.java:1003)
	at javafx.graphics/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at javafx.graphics/javafx.concurrent.Service.lambda$executeTask$6(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/javafx.concurrent.Service.lambda$executeTask$7(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by 0xabdi** [comment]
So, the latter issue was related to my machine details not added to the `mosip_master` database. I added my machine details in the `master-machine_master.csv` file and ran the `update_masterdb.sh` script to update the details in the database. The application restarted and I was able to login with the user `110118 ` and Password `Techno@123`
